apiVersion: apps/v1
kind: Deployment
metadata:
  name: khuranagarv1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khuranagarv1
  template:
    metadata:
      labels:
        app: khuranagarv1
    spec:
      containers:
      - name: khuranagarv1
        image: 970547369783.dkr.ecr.us-east-1.amazonaws.com/garv:latest
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: khuranagarv-service
spec:
  type: LoadBalancer
  selector:
    app: khuranagarv1
  ports:
    - port: 80
      targetPort: 5000
